parameters:
    log_level:  DEBUG
    timezone: Europe/Kiev
    locale: en
    ### Debug: true, false
    ###---------------------
    debug: true
    ### Environment: production, test, development
    ###------------------------------
    environment: test 
    ### Directory data for console
    ###---------------------------
    data_dir:  "c:/tmp"
    ###-- HOST url for local testing
    ###------------------------------
    url_test: "http://localhost:8888"
    ###-- UBKI parameters
    ubki_login: "ubkiuser"
    ubki_pass: "ubkipass"
    ubki_test_login: "partest"
    ubki_test_pass: "test38%"
    ###-- Database parameters
    ###---------------------
    db.driver: pdo_sqlite
    db.path: "/app/Resources/db/app.db"
    db.name: app
#    charset: utf8
    ###-- Only relevant for pdo_mysql, pdo_pgsql, and pdo_oci/oci8 drivers
#    host: localhost
#    port: 3306
#    user: root
#    password: admin123
    ###-- Only relevant for sqlite
    ###-- Email parameters
    ###---------------------
    mail.host: mail.azot.local
    mail.port: 25
    mail.username: m5-asutp
    mail.password: B$A3837m5
    # ('tls', 'ssl', or null)
    mail.encryption: null
    # ('plain', 'login', 'cram-md5', or null)
    mail.auth_mode: null
    # Disabling Sending
    mail.disable_delivery:  true
    
    